- include: prerequisites.yml

- name: Add Docker key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: present

- name: Add Docker PPA
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present

- name: Install Docker
  apt: name=docker-ce update_cache=yes

- name: Adding existing user '{{ docker_user }}' to group 'docker'
  user: name={{ docker_user }}
        groups=docker
        append=yes
  register: mandatory_group_list

- name: Force to reconnect when the list of groups has changed
  shell: 'sleep 1; pkill -u {{ ansible_user }} sshd'
  async: 3
  poll: 2
  when: mandatory_group_list|changed
