- include: prerequisites.yml

- name: Add Docker key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: 'https://download.docker.com/linux/ubuntu/gpg'
    state: present

- name: Add Docker PPA
  apt_repository:
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable'
    state: present

- name: Install Docker
  apt: name=docker-ce update_cache=yes

- include: linux-image-extra.yml

- name: Adding existing user 'vagrant' to group 'docker'
  user: name='vagrant'
        groups=docker
        append=yes
